services:
  n8n:
    stdin_open: true
    tty: true
    container_name: n8n
    network_mode: host
    ports:
      - 5678:5678
    volumes:
      - n8n_data:/home/node/.n8n
    image: docker.n8n.io/n8nio/n8n
    environment:
      - N8N_HOST=0.0.0.0  # Permitir acceso desde cualquier IP
      - N8N_PORT=5678      # Definir el puerto explícitamente
      - N8N_SECURE_COOKIE=false  # Deshabilitar SSL (solo para pruebas)
      - GENERIC_TIMEZONE=Europe/Madrid
      - TZ=Europe/Madrid
    command: ["node", "--max-old-space-size=4096", "/usr/local/bin/n8n"]

volumes:
  n8n_data:
    external: false
    name: n8n_data